### ISSUE TITLE
Change usage in README

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/mockingcase#55]
The **Usage** section is too big and it could grow in future. 
In the main **Usage** section only `mOcKiNgCaSe(input, [options])` usage should be sampled.

Usages for others functionalities of the package should be sampled bellow the API description of functions parameters.

**Comment by maxrumsey** [comment]
Would this be a good replacement for the **Usage** section? Too short or too long? It contains all the important stuff, and all the other stuff I have excluded is stuff that should be covered in the API section.
```
const mOcKiNgCaSe = require('mockingcase');
// es6 - import mOcKiNgCaSe from 'mockingcase';
//  ts - import * as mOcKiNgCaSe from 'mockingcase';
//  ts - import mOcKiNgCaSe = require('mockingcase');

mOcKiNgCaSe('foo-bar');
//=> 'fOo-bAr'

mOcKiNgCaSe('aa', {random: false});
//=> 'aA'

mOcKiNgCaSe('aa', {random: true});
//=> 'aa'
//=> 'aA'
//=> 'Aa'
//=> 'AA'

mOcKiNgCaSe('42foo!bar');
//=> '42fOo!bAr'

mOcKiNgCaSe('aa123', {onlyLetters: true});
//=> 'aA'

mOcKiNgCaSe('a13%$a', {onlyLetters: true});
//=> 'aA'

mOcKiNgCaSe('foo bar', {firstUpper: true});
//=> 'FoO BaR'

mOcKiNgCaSe('foo', {firstUpper: true, random: true});
//=> 'Foo'
//=> 'FOo'
//=> 'FoO'
//=> 'FOO'
```

**Comment by strdr4605** [comment]
@maxrumsey, where do you suggest to put
```js
mOcKiNgCaSe(['foo','bar']);
//=> 'fOoBaR'

mOcKiNgCaSe(undefined);
//=> Error "An input is required"
```

**Comment by maxrumsey** [comment]
I suggest we the put the Array example under this API section: https://github.com/strdr4605/mockingcase#mOcKiNgCaSe. Something like this would work:

## mOcKiNgCaSe(input, [options]) ⇒ string
Converts the input string(s) to mOcKiNgCaSe.

Kind: global function Returns: string - string in mOcKiNgCaSe
[TABLE]
Passing an array as an argument will result in converting the array to a string before being finally converted to mOcKiNgCaSe.
```
mOcKiNgCaSe(['foo','bar']);
//=> 'fOoBaR'
```

And for the undefined input, I suggest we just drop it from the documentation. It's already expected behaviour to throw an error if an argument is missing.

**Comment by strdr4605** [comment]
> Passing an array as an argument will result in converting the array to a string before being finally converted to mOcKiNgCaSe.

Maybe this explanation is not necessary?! 

Also thought about adding to `mOcKiNgCaSe(input, [options]) ⇒ string` not only the 

```js
mOcKiNgCaSe(['foo','bar']);
//=> 'fOoBaR'
```
but also something from the main **Usage** section
